# Базовый образ с CUDA 11.8
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Устанавливаем Python 3.11 из стандартных репозиториев Ubuntu 22.04
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    TRITON_DISABLE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.11 \
    python3.11-dev \
    python3.11-venv \
    python3.11-distutils \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем pip для Python 3.11
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

# Создаем и активируем venv
RUN python3.11 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Устанавливаем зависимости (кешируемый слой)
COPY requirements.txt install_req.sh /tmp/
RUN pip install --upgrade pip setuptools wheel && \
    chmod +x /tmp/install_req.sh && \
    /tmp/install_req.sh  && \
    pip install -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

RUN pip uninstall triton -y

# Настройки CUDA
ENV CUDA_HOME=/usr/local/cuda-11.8 \
    LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH

# Копируем код
WORKDIR /app
COPY . /app

CMD ["python3.11", "lyrical-gpu.py"]